# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: false

# Setup
title:            Pchas
tagline:          'Software and Design'
description:      'visit us at <a href="https://pchas.ir" target="_blank">Pchas</a>. We are on <a href="https://www.instagram.com/pchas.ir/" target="_blank">Instagram</a> and other social medias, @pchas.ir is our username.'
url:              https://pchas.github.io
baseurl:          /

author:
  name:           'Aref Akbari'
  url:            https://pchas.ir

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Pchas/pchas.github.io
